package Vista;

public class VistaLogin extends javax.swing.JFrame {
    
    
    public VistaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        logoName = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        pnlExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        userPass = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setForeground(new java.awt.Color(255, 255, 255));
        pnlMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoName.setBackground(new java.awt.Color(255, 255, 255));
        logoName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoName.setForeground(new java.awt.Color(255, 255, 255));
        logoName.setText("DYNAMI");
        pnlMain.add(logoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 80, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo_1.png"))); // NOI18N
        pnlMain.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, 150));

        city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/city.png"))); // NOI18N
        pnlMain.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        favicon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/favicon.png"))); // NOI18N
        favicon.setText("DYNAMI");
        pnlMain.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setText("INICIAR SESIÓN");
        pnlMain.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));

        pnlExit.setBackground(new java.awt.Color(255, 255, 255));

        lblExit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addGap(0, 749, Short.MAX_VALUE)
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMain.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        userLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userLabel.setText("Correo");
        pnlMain.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));
        pnlMain.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 390, 30));

        txtCorreo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtCorreo.setToolTipText("Correo");
        txtCorreo.setBorder(null);
        pnlMain.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 390, 30));

        userPass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userPass.setText("Contraseña");
        pnlMain.add(userPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));
        pnlMain.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 390, 30));

        txtPass.setForeground(new java.awt.Color(102, 102, 102));
        txtPass.setToolTipText("Contraseña");
        txtPass.setBorder(null);
        pnlMain.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 390, -1));

        pnlLogin.setBackground(new java.awt.Color(0, 134, 190));

        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("ENTRAR");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMain.add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JLabel favicon;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel lblExit;
    public javax.swing.JLabel lblLogin;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoName;
    public javax.swing.JPanel pnlExit;
    public javax.swing.JPanel pnlHeader;
    public javax.swing.JPanel pnlLogin;
    public javax.swing.JPanel pnlMain;
    private javax.swing.JLabel title;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JPasswordField txtPass;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userPass;
    // End of variables declaration//GEN-END:variables

}
